"""empty message

Revision ID: 241ecd04e184
Revises: 307f506cc307
Create Date: 2024-10-02 15:32:23.266431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241ecd04e184'
down_revision = '307f506cc307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_logged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_logged')

    # ### end Alembic commands ###
