"""empty message

Revision ID: dfcf7449ebd5
Revises: b08ad2ee6620
Create Date: 2024-10-01 15:06:21.928725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfcf7449ebd5'
down_revision = 'b08ad2ee6620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('salary')

    # ### end Alembic commands ###
